version: '3'

services:
   mysql:
     image: mysql:5.7.22
     container_name: mysql
     restart: always
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: faveodb
       MYSQL_USER: root
       MYSQL_PASSWORD: password
     ports:
       - "3306:3306"

   faveo:
     container_name: faveo
     depends_on:
       - mysql
     image: faveo-docker
     links:
       - mysql:mysql
     ports:
       - "80:80"
     restart: always


volumes:
    db_data:
